name: Cron # Name of our workflow

on:
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest # Environment job will run in

    steps: # Each action/command to run
      - uses: actions/checkout@v1 # Helps check out the repo code
      - uses: ./.github/actions/daily-action # Tell it to run out JS Action
        env:
          TRELLO_MEMBER: 5c4b60877d421272511a4a80
