# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: schedule daily boards

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  scheduleDailyBoards:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: call makeDailyBoards
        uses: ./actions/action.yml


        #Per 'learn with jason' video, the 'uses' here should point to where the action.yml lives